### ISSUE TITLE
Problem in running the evaluation script

### ISSUE THREAD

**Issue by VIROBO-15** [kohjingyu/gill#9]
I have problem in running the evaluation 

Are saving some images I am getting the Errors in both VIST Evaluation and VisDial Evaluation. 

Saving to /home/mbzuaiser/gill/gill_vist_outputs/2591919314.png ███████████████████████████████████████████▉  | 49/50 [00:02<00:00, 17.59it/s]
  4%|███| 185/4990 [40:27<17:30:59, 13.12s/it]

Traceback (most recent call last):
  File "evals/generate_vist_images.py", line 74, in <module>
    return_outputs = model.generate_for_images_and_texts(
  File "/home/mbzuaiser/gill/gill/models.py", line 688, in generate_for_images_and_texts
    img = utils.get_image_from_url(self.path_array[img_idx])
  File "/home/mbzuaiser/gill/gill/utils.py", line 29, in get_image_from_url
    img = img.resize((224, 224))
  File "/home/mbzuaiser/gill/venv/lib/python3.8/site-packages/PIL/Image.py", line 2138, in resize
    self.load()
  File "/home/mbzuaiser/gill/venv/lib/python3.8/site-packages/PIL/ImageFile.py", line 266, in load
    raise OSError(msg)
OSError: image file is truncated (0 bytes not processed)

Can you Please help me fix this ?

**Comment by kohjingyu** [comment]
This usually means that one of the files used for retrieval is corrupted. You can avoid this by [not running the retrieval head](https://github.com/kohjingyu/gill/blob/0bd94dad92edc9bc69c31a0966f9e5207c3cb262/gill/models.py#L820-L822) (if you're just doing VIST/VisDial evaluation), or [add an except for OSError](https://github.com/kohjingyu/gill/commit/0bd94dad92edc9bc69c31a0966f9e5207c3cb262) (just pushed this to `head`).

I'm closing this, but feel free to reopen it if you're still facing issues.
